language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_script:
  - php coveralls.phar -v
